// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPage.Server.Console.Database;

namespace WebPage.Server.Console.Migrations
{
    [DbContext(typeof(FinanceServiceContext))]
    [Migration("20210528195128_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebPage.Server.FinanceService.DataAccess.ServiceRepository.StockInfo", b =>
                {
                    b.Property<int>("StockInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FirstValueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastRefreshed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StockInfoId");

                    b.ToTable("StockInfos");
                });

            modelBuilder.Entity("WebPage.Server.FinanceService.DataAccess.ServiceRepository.StockPerformance", b =>
                {
                    b.Property<int>("StockPerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StockInfoId")
                        .HasColumnType("int");

                    b.Property<double>("close")
                        .HasColumnType("float");

                    b.Property<DateTime>("valueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StockPerformanceId");

                    b.HasIndex("StockInfoId");

                    b.ToTable("StockPerformance");
                });

            modelBuilder.Entity("WebPage.Server.FinanceService.DataAccess.ServiceRepository.StockPerformance", b =>
                {
                    b.HasOne("WebPage.Server.FinanceService.DataAccess.ServiceRepository.StockInfo", null)
                        .WithMany("Performance")
                        .HasForeignKey("StockInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebPage.Server.FinanceService.DataAccess.ServiceRepository.StockInfo", b =>
                {
                    b.Navigation("Performance");
                });
#pragma warning restore 612, 618
        }
    }
}
