// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPage.Server.Console.Database;

namespace WebPage.Server.Console.Migrations
{
    [DbContext(typeof(FinanceServiceContext))]
    partial class FinanceServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebPage.Server.FinanceService.Data.ServiceRepository.StockInfo", b =>
                {
                    b.Property<int>("StockInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FirstValueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastRefreshed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StockInfoId");

                    b.ToTable("StockInfos");
                });

            modelBuilder.Entity("WebPage.Server.FinanceService.Data.ServiceRepository.StockPerformance", b =>
                {
                    b.Property<int>("StockPerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StockInfoId")
                        .HasColumnType("int");

                    b.Property<double>("close")
                        .HasColumnType("float");

                    b.Property<DateTime>("valueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StockPerformanceId");

                    b.ToTable("StockPerformance");
                });
#pragma warning restore 612, 618
        }
    }
}
